import Link from 'next/link';

// The projected README (docs-site/content/docs/index.mdx, generated by
// scripts/project_docs_to_mdx.py from the repo's README.md) IS the site's
// real home page — its own Purpose line says so ("Also the home page the
// hosted docs site renders"). This top-level route stays a thin landing
// that sends visitors straight there.
export default function HomePage() {
  return (
    <div className="flex flex-col justify-center text-center flex-1 gap-4">
      <h1 className="text-2xl font-bold">sartor.</h1>
      <p>
        Local-first résumé + cover-letter tailoring, grounded in your real
        history.{' '}
        <Link href="/docs" className="font-medium underline">
          Read the docs
        </Link>
        .
      </p>
    </div>
  );
}
