"""initial schema — full career corpus + candidate memory

Revision ID: 0001
Revises:
Create Date: 2026-05-12

Creates all 24 tables from db.models.Base.metadata in one shot. Future
migrations should be autogenerated (`alembic revision --autogenerate -m "..."`)
and add granular alter steps.

Rationale: this is the v0.3.0 big-bang cutover; there is no pre-existing
DB schema to delta against, so materializing the full metadata in one
revision is both simpler and faithfully equivalent to a hand-rolled
sequence of `op.create_table` calls.
"""
from __future__ import annotations

from collections.abc import Sequence

from db.models import Base

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    from alembic import op

    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    from alembic import op

    Base.metadata.drop_all(bind=op.get_bind())
