import { createOpenAPI } from 'fumadocs-openapi/server';

// docs-site/openapi.json is generated by scripts/generate_openapi_spec.py (repo
// root) BEFORE this app builds — see .github/workflows/docs-deploy.yml. It is a
// pure function of the 5 spectree-decorated Flask routes at HEAD (a gitignored
// build artifact, not a second source of truth; same division of labor as
// scripts/project_docs_to_mdx.py's L1 -> MDX projection).
//
// docs-site/scripts/generate-api-docs.mjs is a SEPARATE, standalone
// `createOpenAPI()` caller — it cannot use this module's `@/lib/openapi` path
// alias, since it runs as a plain Node script outside Next's bundler, not
// through `next build`. THIS instance is the one consumed at render time by
// app/docs/[[...slug]]/page.tsx via `openapi.preloadOpenAPIPage(page)`.
//
// The schema ID here MUST be the literal string `"api"` — it has to match the
// key generate-api-docs.mjs registers its `createOpenAPI({ input: { api: ...
// } })` call under, because that script bakes this same ID into each
// generated page's `_openapi.preload` list and its `document="api"` JSX prop.
// `preloadOpenAPIPage()` looks up each `preload` entry against *this*
// instance's `resolvedInput` map by exact key match — a mismatch (e.g. one
// side using a bare file path as its own key) silently falls through to an
// uncached, unlisted-schema warning path instead of the fast cached lookup.
export const openapi = createOpenAPI({
  input: {
    api: './openapi.json',
  },
});
