#!/usr/bin/env python3
"""Is the local docs-site projection current? (item 126)

`docs-site/content/docs/*.mdx` is generated by `scripts/project_docs_to_mdx.py` and
gitignored, so a local copy can be months old and still look like the live site. A D1 audit
read exactly such a copy as the published site and its headline finding was void. Each
projected page now carries `sourceCommit` (the commit it was projected from, with
`+uncommitted` if the sources had local edits). This compares the stamps to HEAD.

Run before you read or cite the local projection: `python scripts/check_docs_projection_fresh.py`.
Exit 0 when every page was projected from HEAD with no uncommitted source edits. Exit 1 when
pages are stale, unstamped (projected before item 126) or mixed. Exit 2 when there is no
projection at all.

**Known limit (C-0):** nothing forces this to run before someone reads the files. The stamp
in every page's banner is the always-visible half; this script is the explicit check.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTENT_DIR = REPO_ROOT / "docs-site" / "content" / "docs"
_STAMP_RE = re.compile(r'^sourceCommit: "([^"]+)"$', re.M)


def stamps(content_dir: Path = CONTENT_DIR) -> dict[str, str | None]:
    """Page filename -> its `sourceCommit`, or None when the page has no stamp."""
    out: dict[str, str | None] = {}
    for page in sorted(content_dir.glob("*.mdx")):
        text = page.read_text(encoding="utf-8")
        # The stamp lives in the YAML frontmatter, which can run long (a long Purpose).
        end = text.find("\n---\n", 4) if text.startswith("---\n") else -1
        m = _STAMP_RE.search(text[:end]) if end != -1 else None
        out[page.name] = m.group(1) if m else None
    return out


def verdict(page_stamps: dict[str, str | None], head: str) -> tuple[bool, str]:
    """(fresh?, one-line reason). Pure, so it is unit-tested without a projection."""
    if not page_stamps:
        return False, "no projected pages"
    unstamped = [p for p, s in page_stamps.items() if s is None]
    if unstamped:
        return False, f"{len(unstamped)} page(s) carry no sourceCommit (projected before item 126)"
    distinct = {s for s in page_stamps.values() if s is not None}
    if len(distinct) > 1:
        return False, f"pages come from {len(distinct)} different projections: {sorted(distinct)}"
    (stamp,) = distinct
    if stamp.endswith("+uncommitted"):
        return False, f"projected from uncommitted edits on top of {stamp.split('+')[0][:12]}"
    if stamp != head:
        return False, f"projected from {stamp[:12]}, HEAD is {head[:12]}"
    return True, f"projected from HEAD ({head[:12]})"


def main() -> int:
    if not CONTENT_DIR.is_dir():
        print(
            "check_docs_projection_fresh: no projection — run python scripts/project_docs_to_mdx.py"
        )
        return 2
    head = subprocess.run(
        ["git", "rev-parse", "HEAD"],  # noqa: S607 - `git` resolved from PATH
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    fresh, reason = verdict(stamps(), head)
    if fresh:
        print(f"check_docs_projection_fresh: OK — {reason}.")
        return 0
    print(
        f"check_docs_projection_fresh: STALE — {reason}. "
        "Re-run python scripts/project_docs_to_mdx.py before reading it as current."
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
